### ISSUE TITLE
About sd1.5 based mvdream support

### ISSUE THREAD

**Issue by Yzhbuaa** [lizhiqi49/mvdream-diffusers#1]
Hello,

Thank you for your excellent work! Have you tested your implementation on the SD1.5-based MVDream model? I appreciate your time and assistance.

Thank you!

**Comment by lizhiqi49** [comment]
To use this implementation for mvdream, the key point is converting the keys of original mvdream checkpoint to that supported by diffusers. I only do this conversion for sd2.1 ckpt, and this implementation should be OK if given a converted sd1.5 ckpt.  :)

**Comment by Yzhbuaa** [comment]
Hello Zhiqi,

Could you please share your conversion code with me? I am planning to enhance it with support for SD 1.5. Thank you!

**Comment by lizhiqi49** [comment]
I'd like to, but I did the conversion within ipython command line, so I don't have a script left...

However, I know the diffusers repo has the script for conversion between the implementation of vanilla SD and diffusers, you can refer to it.
